language: php

php:
  - 5.6

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache